quark/jasmin/urls.py
#  Copyright (c) 2025
#  File created on 2025/4/26
#  By: Emmanuel Keeya
#  Email: ekeeya@thothcode.tech
#
#  This project is licensed under the GNU General Public License v3.0. You may
#  redistribute it and/or modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with this project.
#  If not, see <http://www.gnu.org/licenses/>.
#

from .views import (
    JasminGroupCRUDL,
    JasminUserCRUDL,
    JasminSMPPConnectorCRUDL,
    JasminHTTPConnectorCRUDL,
    JasminFilterCRUDL,
    JasminRouteCRUDL,
    JasminInterceptorCRUDL
)

urlpatterns = JasminGroupCRUDL().as_urlpatterns()
urlpatterns += JasminUserCRUDL().as_urlpatterns()
urlpatterns += JasminSMPPConnectorCRUDL().as_urlpatterns()
urlpatterns += JasminHTTPConnectorCRUDL().as_urlpatterns()
urlpatterns += JasminFilterCRUDL().as_urlpatterns()
urlpatterns += JasminRouteCRUDL().as_urlpatterns()
urlpatterns += JasminInterceptorCRUDL().as_urlpatterns()

quark/urls.py
from django.conf import settings
from django.conf.urls.static import static
#
#  Copyright (c) 2024
#  File created on 2024/7/17
#  By: Emmanuel Keeya
#  Email: ekeeya@thothcode.tech
#
#  This project is licensed under the GNU General Public License v3.0. You may
#  redistribute it and/or modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with this project.
#  If not, see <http://www.gnu.org/licenses/>.
#

from django.contrib import admin
from django.urls import path
from django.urls.conf import include, re_path


urlpatterns = [
    path('', include('quark.web.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('quark.api.urls')),
]

urlpatterns +=[
    re_path(r"^", include("quark.workspace.urls")),
    re_path(r"^", include("quark.jasmin.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quark/jasmin/views/forms.py
#  Copyright (c) 2025
#  File created on 2025/4/26
#  By: Emmanuel Keeya
#  Email: ekeeya@thothcode.tech
#
#  This project is licensed under the GNU General Public License v3.0. You may
#  redistribute it and/or modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with this project.
#  If not, see <http://www.gnu.org/licenses/>.
#
import re

from django import forms
from django.utils.text import slugify

from quark.jasmin.models import JasminGroup, JasminUser, JasminSMPPConnector, JasminFilter, JasminRoute, \
    JasminInterceptor, JasminHTTPConnector
from quark.jasmin.views.sub_forms import MessagingAuthorizationsForm, MessagingValueFiltersForm, MessagingDefaultsForm, \
    MessagingQuotasForm, SMPPAuthorizationsForm, SMPPQuotasForm
from quark.utils.fields import SelectWidget
from quark.workspace.views.forms import BaseWorkspaceForm


class JasminGroupForm(BaseWorkspaceForm):
    gid = forms.CharField(
        label="UID*",
        max_length=JasminGroup._meta.get_field("gid").max_length,
        help_text=JasminGroup._meta.get_field("gid").help_text,
        widget=forms.TextInput(attrs={
            "required": True,
            "widget_only": True,
            "placeholder": "test_group"
        }),
    )

    def clean_gid(self):
        gid = self.cleaned_data["gid"]
        prefix = f"g{self.workspace.id}"
        clean_name = f"{prefix}_{slugify(gid)}".lower()
        regex = re.compile(r'^[A-Za-z0-9_-]{1,16}$')

        if not regex.match(clean_name):
            raise forms.ValidationError(
                f"Group ID must be 1-16 characters long and contain only letters, numbers, underscores, or hyphens."
                f" Note that we also prefix it with {prefix}_"
            )

        # Check for existing group
        if JasminGroup.objects.filter(gid=clean_name).exists():
            raise forms.ValidationError(f"JasminGroup with name {gid} already exists")

        return clean_name

    def clean(self):
        self.cleaned_data['workspace'] = self.workspace
        return self.cleaned_data

    class Meta:
        model = JasminGroup
        fields = ('gid', 'description')


class UpdateJasminGroupForm(BaseWorkspaceForm):
    class Meta:
        model = JasminGroup
        fields = ('description',)  # we can only update the description


class JasminUserForm(BaseWorkspaceForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Must conform to our workspace.
        self.fields['group'].queryset = self.workspace.jasmin_groups
        # Get the data for subforms
        mt_data = self.instance.mt_credential if self.instance.pk else {}
        smpps_data = self.instance.smpps_credential if self.instance.pk else {}

        # Initialize subforms with data if this is a POST request i.e when form is bound
        if self.is_bound:
            self.mt_auth_form = MessagingAuthorizationsForm(
                data=self.data, prefix='mt_auth')
            self.mt_filter_form = MessagingValueFiltersForm(
                data=self.data, prefix='mt_filter')
            self.mt_default_form = MessagingDefaultsForm(
                data=self.data, prefix='mt_default')
            self.mt_quota_form = MessagingQuotasForm(
                data=self.data, prefix='mt_quota')

            self.smpps_auth_form = SMPPAuthorizationsForm(
                data=self.data, prefix='smpps_auth')
            self.smpps_quota_form = SMPPQuotasForm(
                data=self.data, prefix='smpps_quota')
        else:
            # For GET requests, use initial data
            self.mt_auth_form = MessagingAuthorizationsForm(
                initial=mt_data.get('authorizations', {}), prefix='mt_auth')
            self.mt_filter_form = MessagingValueFiltersForm(
                initial=mt_data.get('value_filters', {}), prefix='mt_filter')
            self.mt_default_form = MessagingDefaultsForm(
                initial=mt_data.get('defaults', {}), prefix='mt_default')
            self.mt_quota_form = MessagingQuotasForm(
                initial=mt_data.get('quotas', {}), prefix='mt_quota')

            self.smpps_auth_form = SMPPAuthorizationsForm(
                initial=smpps_data.get('authorizations', {}), prefix='smpps_auth')
            self.smpps_quota_form = SMPPQuotasForm(
                initial=smpps_data.get('quotas', {}), prefix='smpps_quota')

    def clean(self):
        cleaned_data = super().clean()

        # Validate mt_credentials subforms
        mt_forms = [
            (self.mt_auth_form, 'Messaging Authorizations'),
            (self.mt_filter_form, 'Messaging Value Filters'),
            # (self.mt_default_form, 'Messaging Defaults'),
            (self.mt_quota_form, 'Messaging Quotas'),
        ]
        for form, label in mt_forms:
            if not form.is_valid():
                errors = []
                for field, field_errors in form.errors.items():
                    for error in field_errors:
                        errors.append(f"{field}: {error}")
                raise forms.ValidationError(f"Invalid {label}: {', '.join(errors)}")

        # Validate smpps_credential subforms
        smpps_forms = [
            (self.smpps_auth_form, 'SMPP Authorizations'),
            (self.smpps_quota_form, 'SMPP Quotas'),
        ]
        for form, label in smpps_forms:
            if not form.is_valid():
                errors = []
                for field, field_errors in form.errors.items():
                    for error in field_errors:
                        errors.append(f"{field}: {error}")
                raise forms.ValidationError(f"Invalid {label}: {', '.join(errors)}")

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        # Construct mt_credential
        instance.mt_credential = {
            'authorizations': self.mt_auth_form.cleaned_data,
            'value_filters': self.mt_filter_form.cleaned_data,
            # 'defaults': self.mt_default_form.cleaned_data,
            'quotas': self.mt_quota_form.cleaned_data,
        }

        # Construct smpps_credential
        instance.smpps_credential = {
            'authorizations': self.smpps_auth_form.cleaned_data,
            'quotas': self.smpps_quota_form.cleaned_data,
        }

        if commit:
            instance.save()
        return instance

    class Meta:
        model = JasminUser
        fields = ('username', 'password', 'group', 'mt_credential', 'smpps_credential')


class JasminSPPConnectorForm(BaseWorkspaceForm):

    def clean(self):
        self.cleaned_data['workspace'] = self.workspace
        log_file = self.cleaned_data['log_file']
        if log_file == '':
            # if log file is not set leave it upto jasmin to default it
            del self.cleaned_data['log_file']
        return self.cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)

        # add workspace to instance
        instance.workspace = self.cleaned_data['workspace']

        if commit:
            instance.save()
        return instance

    class Meta:
        model = JasminSMPPConnector
        exclude = ("cid", "workspace", "connector_type", "created_by", 'modified_by')


class JasminHttpConnectorForm(BaseWorkspaceForm):

    def save(self, commit=True):
        instance = super().save(commit=False)

        # add workspace to instance
        instance.workspace = self.cleaned_data['workspace']

        if commit:
            instance.save()
        return instance

    class Meta:
        model = JasminHTTPConnector
        exclude = ("cid", "workspace", "connector_type", "created_by", 'modified_by', 'is_active')


class JasminFilterForm(BaseWorkspaceForm):
    # Add these fields for the JSON param input
    param_key = forms.CharField(
        required=False,
        label="Parameter Key",
        initial=None,
        help_text="Enter the parameter key",
    )
    param_value = forms.CharField(
        required=False,
        initial=None,
        label="Parameter Value",
        help_text="Enter the parameter value",
        widget=forms.TextInput(attrs={'class': 'param-value-input'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # If we're editing an existing instance, pre-populate the param fields
        if self.instance and self.instance.param:
            self.fields['param_key'].initial = self.instance.param.get('key', '')
            self.fields['param_value'].initial = self.instance.param.get('value', '')

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data['workspace'] = self.workspace

        # Validate that if either key or value is provided, both must be provided
        param_key = cleaned_data.get('param_key')
        param_value = cleaned_data.get('param_value')

        if bool(param_key) != bool(param_value):
            raise forms.ValidationError(
                "Both parameter key and value must be provided together or left blank"
            )

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)

        # Construct the param JSON from the form inputs
        param_key = self.cleaned_data.get('param_key')
        param_value = self.cleaned_data.get('param_value')

        if param_key and param_value:
            instance.param = {'key': param_key, 'value': param_value}
        else:
            instance.param = None

        # add workspace to instance

templates/jasmin/filters/filter_create.html
<div class="p-2 overflow-y-auto space-y-2">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="space-y-1">
            <label for="{{ form.fid.id_for_label }}" class="block text-sm font-medium text-gray-700">
                {{ form.fid.label }}
                {% if form.fid.field.required %}<span class="text-red-500">*</span>{% endif %}
            </label>
            {{ form.fid }}
            {% if form.username.help_text %}
                <span style="font-size: 6pt !important;" class="text-gray-500">{{ form.fid.help_text }}</span>
            {% endif %}

            <div style="font-size: 6pt !important;" data-modal-error="{{ form.fid.name }}"
                 class="hidden text-red-600"></div>
        </div>

        <div class="space-y-1">
            <label for="{{ form.nature.id_for_label }}" class="block text-sm font-medium text-gray-700">
                {{ form.nature.label }}
                {% if form.nature.field.required %}<span class="text-red-500">*</span>{% endif %}
            </label>
            {{ form.nature }}
            {% if form.nature.help_text %}
                <span style="font-size: 6pt !important;" class="text-gray-500">{{ form.nature.help_text }}</span>
            {% endif %}

            <div style="font-size: 6pt !important;" data-modal-error="{{ form.nature.name }}"
                 class="hidden text-red-600"></div>
        </div>
    </div>
    <div class="space-y-1">
        <label for="{{ form.filter_type.id_for_label }}" class="block text-sm font-medium text-gray-700">
            {{ form.filter_type.label }}
            {% if form.filter_type.field.required %}<span class="text-red-500">*</span>{% endif %}
        </label>
        {{ form.filter_type }}
        {% if form.filter_type.help_text %}
            <span style="font-size: 6pt !important;" class="text-gray-500">{{ form.filter_type.help_text }}</span>
        {% endif %}
        <div style="font-size: 6pt !important;" data-modal-error="{{ form.filter_type.name }}"
             class="hidden text-red-600"></div>
    </div>
    <div class="grid grid-cols-1 hidden" id="show-args">
        <fieldset class="space-y-4">
            <legend class="text-lg font-medium text-gray-900">Filter Arguments</legend>
            <div role="alert" class="alert alert-dash alert-warning text-xs flex flex-row">
                If a filter type requires argument specify the key and value below or leave these empty
                <a class="text-blue-500 underline"
                   href="https://docs.jasminsms.com/en/latest/management/jcli/modules.html#filter-manager"
                   target="_blank">Docs</a>
            </div>
            <div class="space-y-1">
                <label for="{{ form.param_key.id_for_label }}" class="block text-sm font-medium text-gray-700">
                    {{ form.param_key.label }}
                    {% if form.param_key.field.required %}<span class="text-red-500">*</span>{% endif %}
                </label>
                {{ form.param_key }}
                {% if form.param_key.help_text %}
                    <span style="font-size: 6pt !important;" class="text-gray-500">{{ form.param_key.help_text }}</span>
                {% endif %}

                <div style="font-size: 6pt !important;" data-modal-error="{{ form.param_key.name }}"
                     class="hidden text-red-600"></div>
            </div>
            <div class="space-y-1 md:col-span-2">
                <label for="{{ form.param_value.id_for_label }}" class="block text-sm font-medium text-gray-700">
                    {{ form.param_value.label }}
                    {% if form.param_value.field.required %}<span class="text-red-500">*</span>{% endif %}
                </label>
                {{ form.param_value }}
                {% if form.param_value.help_text %}
                    <span style="font-size: 6pt !important;"
                          class="text-gray-500">{{ form.param_value.help_text }}</span>
                {% endif %}
                <div style="font-size: 6pt !important;" data-modal-error="{{ form.param_value.name }}"
                     class="hidden text-red-600"></div>
            </div>
        </fieldset>
    </div>
    <div id="filter-info" class="alert-info alert-dash alert-outline m-2 hidden alert text-xs"></div>
</div>
<script>
    $(document).ready(function () {
        const allFilters = [
            ["TransparentFilter", null, "This filter will always match any message criteria"],
            ["SourceAddrFilter", {source_addr: "^20d+"}, "Will match the source address of a MO message. arg source_addr: is a regular expression to match source address"],
            ["DestinationAddrFilter", {destination_addr: "^85111$"}, "Will match the destination address of a MT message. destination_addr: is a regular expression to match destination address"],
            ["ShortMessageFilter", {short_message: "^hello.*$"}, "Will match the content of a message. short_message: is a regular expression to match message content"],
            ["DateIntervalFilter", {dateInterval: "2025-05-01;2025-05-16"}, "Will match the date of a message. dateInterval: are Two dates separated by ; (date format is YYYY-MM-DD)"],
            ["TimeIntervalFilter", {timeInterval: "08:00:00;18:00:00"}, "Will match the time of a message. timeInterval: Two timestamps separated by ; (timestamp format is HH:MM:SS)"],
            ["TagFilter", {tag: 32401}, "Will check if message has a defined tag. tag: numeric tag to match in message"],
            ["EvalPyFilter", {pyCode: "/var/filters/thirdparty.py"}, "Will pass the message to a third party python script for user-defined filtering. pyCode:file system path to a python script,"]
        ];
        const moFilters = [
            ["ConnectorFilter", {cid: "smppc_1_1"}, "Will match the source connector of a message. cid: cid of the connector to match"]
        ]
        const mtFilters = [
            ["UserFilter", {uid: "user_uid"}, "Will match the owner of a MT message. uid:uid of the user to match"],
            ["GroupFilter", {gid: "group_gid"}, "Will match the owner’s group of a MT message. gid:gid of the group to match"]
        ]
        let applyFilters = allFilters;
        setFilterTypeOptions()
        $("#id_nature").on("change", function (e) {
            const opt = e.target.value
            switch (opt) {
                case "MT":
                    applyFilters = mtFilters;
                    break;
                case "MO":
                    applyFilters = moFilters;
                    break;
                default:
                    applyFilters = allFilters
                    break;
            }
            setFilterTypeOptions();
        })
        let selectedFilter = {}

        $("#id_filter_type").on("change", function (e) {
            const selectedOption = $(this).find('option:selected');
            const index = selectedOption.data("index");
            selectedFilter = applyFilters[index]
            // auto populate the key, value fields
            const attributes = selectedFilter[1]
            let key= ""
            let value =""
            if (attributes) {
                key = Object.keys(attributes)[0];
                value = attributes[key];
                $("#show-args").show("delay")
            } else {
                $("#show-args").hide("delay")
            }
            $("#id_param_key").val(key);
                $("#id_param_value").val(value);
            $("#filter-info").html(selectedFilter[2])
            $("#filter-info").show("slow")
        })

        function setFilterTypeOptions() {
            let options = "<option>---Select Filter---</option>"
            applyFilters.forEach((filter, index) => {
                options += `<option data-index="${index}"  value="${filter[0]}">${filter[0]}</option>`
            })
            $("#id_filter_type").html(options)
        }


    });
</script>

templates/jasmin/filters/filters.html
{% extends 'includes/list.html' %}

{% load smartmin i18n %}

{% block pre-table %}
    <div class="bg-white w-full mb-1 p-2">
        <label class="font-bold uppercase">Filters</label>
        <div role="alertdialog" class="alert alert-info alert-outline">
            <span class="icon-info text-lg"></span>
           <span class="text-xs">
               Filters are used by MO/MT routers to help decide on which route a message must be delivered.
           </span>
        </div>
    </div>
{% endblock pre-table %}

{% block table %}
    <div class="overflow-x-auto">
        <table class="w-full text-sm text-left border border-gray-200 rounded-lg">
            <thead class="text-xs font-semibold uppercase bg-gray-800 text-gray-100">
            <tr>
                {% for field in fields %}
                    <th class="px-3 py-2 border-b border-r border-gray-200 last:border-r-0 {% if view|field_orderable:field %}cursor-pointer hover:bg-gray-700{% endif %}"
                        scope="col"
                        {% if view|field_orderable:field %}onclick="orderBy('{{ field }}')"{% endif %}>
                        {% get_label field %}
                    </th>
                {% endfor %}
                {% if actions %}
                    <th class="px-3 py-2 border-b border-gray-200 text-center">
                        Actions
                    </th>
                {% endif %}
            </tr>
            </thead>
            <tbody class="bg-white">
            {% for obj in object_list %}
                <tr data-pk="{{ obj.id }}" data-row-{{ obj.id }}="{{ obj.cid }}"
                    class="border-b border-gray-200 hover:bg-gray-50 {% cycle 'bg-gray-50' 'bg-white' %} {% if not obj.is_active and obj|is_smartobject %}opacity-60{% endif %}">
                    {% for field in fields %}
                        <td class="px-3 py-2 border-r border-gray-200 last:border-r-0 text-gray-900 ">
                        {% get_value obj field as result %}
                        {{ result|safe }}
                        </td>
                    {% endfor %}
                    {% if actions %}
                        {% include 'includes/table-actions.html' %}
                    {% endif %}
                </tr>
            {% empty %}
                <tr>
                    <td colspan="{{ fields|length|add:1 }}"
                        class="text-center py-4 text-gray-500 border-b border-gray-200">
                        {% trans "No results found" %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}